### ISSUE TITLE
Can not guess which adapter should be used, please choose one of "jasmine,mocha" or apply your own adapter.

### ISSUE THREAD

**Issue by fengmk2** [totorojs/totoro#135]
Test env: http://ci.cnpmjs.org:9999/

```
$ totoro --host ci.cnpmjs.org --port 9999
info handle-cfg.js:203 | Found runner < /Users/mk2/git/totoro/examples/mocha/tests/runner.html >
info index.js:115 | Specified browsers automatically [ 'phantom' ]
error index.js:112 | Adapter error. { orderId: 'SlFKwcP3vXpHAfA-XpLi',
  path: '/tests/runner.html',
  message: 'Can not guess which adapter should be used, please choose one of "jasmine,mocha" or apply your own adapter.' }
/Users/mk2/git/totoro/lib/logger.js:32
        throw new Error(data.message)
              ^
Error: Adapter error. { orderId: 'SlFKwcP3vXpHAfA-XpLi',
  path: '/tests/runner.html',
  message: 'Can not guess which adapter should be used, please choose one of "jasmine,mocha" or apply your own adapter.' }
    at Object.module.exports.tracer.colorConsole.transport (/Users/mk2/git/totoro/lib/logger.js:32:15)
    at module.exports._log (/Users/mk2/git/totoro/node_modules/tracer/lib/console.js:66:18)
    at Object.error (/Users/mk2/git/totoro/node_modules/tracer/lib/console.js:110:13)
    at /Users/mk2/git/totoro/lib/index.js:112:26
    at Array.forEach (native)
    at SocketNamespace.<anonymous> (/Users/mk2/git/totoro/lib/index.js:103:13)
    at SocketNamespace.EventEmitter.emit [as $emit] (/Users/mk2/git/totoro/node_modules/socket.io-client/lib/events.js:165:15)
    at SocketNamespace.onPacket (/Users/mk2/git/totoro/node_modules/socket.io-client/lib/namespace.js:182:20)
    at Socket.onPacket (/Users/mk2/git/totoro/node_modules/socket.io-client/lib/socket.js:443:30)
    at Transport.onPacket (/Users/mk2/git/totoro/node_modules/socket.io-client/lib/transport.js:98:17)
```

**Comment by fengmk2** [comment]
http://ci.cnpmjs.org:9999/

**Comment by fool2fish** [comment]
当前依赖的 socket.io 和不兼容 node v0.11.x，node 正式发布后再更新 socket.io 的依赖。见 #136
